
spring:
  datasource:
    username: root
    password: czhroot
    url: jdbc:mysql://101.200.204.47/flowable2?serverTimezone=Asia/Shanghai&useSSL=false&nullCatalogMeansCurrent=true

# 关闭定时任务JOB
flowable:
  async-executor-activate: false
  # 将databaseSchemaUpdate设置为true。当Flowable发现库与数据库表结构不一致时，会自动将数据库表结构升级至新版本。
  database-schema-update: true
  common:
    app:
      security:
        type: idm
      role-prefix:
      idm-admin:
        user: admin
        password: 123456

